version: '3.3'
services:
  mysql-test:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'tutorials'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - mysql-test:/var/lib/mysql
  mysql-prod:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'tutorials'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-prod:/var/lib/mysql
volumes:
  mysql-test:
  mysql-prod:

